### ISSUE TITLE
How to configure the api key ?

### ISSUE THREAD

**Issue by Chrisdeparis** [WebDevSimplified/React-Firebase-Auth#12]
When i make npm start i got a white page and in the console t {code: "auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly.", a: null}
How to make the .env file ?

**Comment by oliv2915** [comment]
In his YouTube video, he goes over the steps to create this file. https://youtu.be/PKwu15ldZ7k?t=264

**Comment by Chrisdeparis** [comment]
Thanks i found out...😂😂

Le lun. 19 avr. 2021 à 01:44, Brian Oliver II ***@***.***> a
écrit :

**Comment by Yasin-97** [comment]
in the case your issue is resolved, close it!

**Comment by Chrisdeparis** [comment]
Issue is resolved.
